computeMatrix reference-point -b 4000 -a 4000 -R Peaks_Anno_bed/Coatis_1_Active_Promoter_peaks.bed Peaks_Anno_bed/Coatis_2_Weak_Promoter_peaks.bed Peaks_Anno_bed/Coatis_3_Poised_Promoter_peaks.bed Peaks_Anno_bed/Coatis_4_5_Strong_Enhancer_peaks.bed Peaks_Anno_bed/Coatis_6_7_Weak_Enhancer_peaks.bed Peaks_Anno_bed/Coatis_8_Insulator_peaks.bed Peaks_Anno_bed/Coatis_9_Txn_Transition_peaks.bed Peaks_Anno_bed/Coatis_10_Txn_Elongation_peaks.bed Peaks_Anno_bed/Coatis_11_Weak_Txn_peaks.bed Peaks_Anno_bed/Coatis_12_Repressed_peaks.bed Peaks_Anno_bed/Coatis_13_Heterochrom_lo_peaks.bed Peaks_Anno_bed/Coatis_14_15_Repetitive_CNV_peaks.bed  -S ../../../K562_0.1_FA/one-dimensional/mapping/all_reps/K562_0.1FA_allreps_RPKM_10bp.bw --skipZeros -o K562_Coatis_Anno.gz --outFileSortedRegions K562_Coatis_Anno.bed -p 20 --missingDataAsZero
computeMatrix reference-point -b 4000 -a 4000 -R Peaks_Anno_bed/PRO_1_Active_Promoter_peaks.bed Peaks_Anno_bed/PRO_2_Weak_Promoter_peaks.bed Peaks_Anno_bed/PRO_3_Poised_Promoter_peaks.bed Peaks_Anno_bed/PRO_4_5_Strong_Enhancer_peaks.bed Peaks_Anno_bed/PRO_6_7_Weak_Enhancer_peaks.bed Peaks_Anno_bed/PRO_8_Insulator_peaks.bed Peaks_Anno_bed/PRO_9_Txn_Transition_peaks.bed Peaks_Anno_bed/PRO_10_Txn_Elongation_peaks.bed Peaks_Anno_bed/PRO_11_Weak_Txn_peaks.bed Peaks_Anno_bed/PRO_12_Repressed_peaks.bed Peaks_Anno_bed/PRO_13_Heterochrom_lo_peaks.bed Peaks_Anno_bed/PRO_14_15_Repetitive_CNV_peaks.bed  -S ../../../../../literature/K562/PRO_seq/hg38/mapping/K562_PRO_seq_SRR8137173_10bp.bw --skipZeros -o K562_PRO_Anno.gz --outFileSortedRegions K562_PRO_Anno.bed -p 20 --missingDataAsZero
computeMatrix reference-point -b 4000 -a 4000 -R Peaks_Anno_bed/RChIP_1_Active_Promoter_peaks.bed Peaks_Anno_bed/RChIP_2_Weak_Promoter_peaks.bed Peaks_Anno_bed/RChIP_3_Poised_Promoter_peaks.bed Peaks_Anno_bed/RChIP_4_5_Strong_Enhancer_peaks.bed Peaks_Anno_bed/RChIP_6_7_Weak_Enhancer_peaks.bed Peaks_Anno_bed/RChIP_8_Insulator_peaks.bed Peaks_Anno_bed/RChIP_9_Txn_Transition_peaks.bed Peaks_Anno_bed/RChIP_10_Txn_Elongation_peaks.bed Peaks_Anno_bed/RChIP_11_Weak_Txn_peaks.bed Peaks_Anno_bed/RChIP_12_Repressed_peaks.bed Peaks_Anno_bed/RChIP_13_Heterochrom_lo_peaks.bed Peaks_Anno_bed/RChIP_14_15_Repetitive_CNV_peaks.bed -S ../../../../../literature/K562/R_chip/mapping/bam2/K562_D210N_V5ChIP_SRR5379780_Rep1_RPKM_10bp.bw --skipZeros -o K562_RChIP_Anno.gz --outFileSortedRegions K562_RChIP_Anno.bed -p 20 --missingDataAsZero 
computeMatrix reference-point -b 4000 -a 4000 -R Peaks_Anno_bed/PolII_1_Active_Promoter_peaks.bed Peaks_Anno_bed/PolII_2_Weak_Promoter_peaks.bed Peaks_Anno_bed/PolII_3_Poised_Promoter_peaks.bed Peaks_Anno_bed/PolII_4_5_Strong_Enhancer_peaks.bed Peaks_Anno_bed/PolII_6_7_Weak_Enhancer_peaks.bed Peaks_Anno_bed/PolII_8_Insulator_peaks.bed Peaks_Anno_bed/PolII_9_Txn_Transition_peaks.bed Peaks_Anno_bed/PolII_10_Txn_Elongation_peaks.bed Peaks_Anno_bed/PolII_11_Weak_Txn_peaks.bed Peaks_Anno_bed/PolII_12_Repressed_peaks.bed Peaks_Anno_bed/PolII_13_Heterochrom_lo_peaks.bed Peaks_Anno_bed/PolII_14_15_Repetitive_CNV_peaks.bed  -S ../../../../../literature/K562/ChIP_seq/hg38/processed_byself/mapping/bam2/K562_POLR2A_ChIP_Rep1_RPKM_10bp.bw --skipZeros -o K562_PolII_Anno.gz --outFileSortedRegions K562_PolII_Anno.bed -p 20 --missingDataAsZero

plotProfile -m K562_Coatis_Anno.gz -out K562_Coatis_Anno.pdf --plotHeight 15
plotProfile -m K562_PRO_Anno.gz -out K562_PRO_Anno.pdf --plotHeight 15
plotProfile -m K562_RChIP_Anno.gz -out K562_RChIP_Anno.pdf --plotHeight 15
plotProfile -m K562_PolII_Anno.gz -out K562_PolII_Anno.pdf --plotHeight 15
